services:
  - type: web
    name: rust-upload-server
    env: cargo
    plan: free
    buildCommand: "cargo build --release"
    startCommand: "cargo run --release"
    envVars:
      - key: HOST_URL
        value: https://mon-serveur-rust.onrender.com
